select B.WRITER_ID, U.NICKNAME, sum(B.PRICE) TOTAL_SALES
from USED_GOODS_BOARD B
join USED_GOODS_USER U on B.WRITER_ID = U.USER_ID
where (B.STATUS like 'DONE') 
group by B.WRITER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES;